#!/bin/sh

SVNBASE=https://subversion.tecgraf.puc-rio.br/engdist/
#SVN_URL=$SVNBASE/loop/trunk
SVN_URL=/Users/maia/Work/loop/trunk
TEMPDIR=deleteme

svn export --force $SVN_URL $TEMPDIR

for rs in $TEMPDIR/etc/*.rockspec
do
	pn=${rs%%.rockspec}
	pn=${pn##$TEMPDIR/etc/}
	mkdir $pn
	for lf in `lua $TEMPDIR/etc/listfiles.lua $rs`
	do
		cp $TEMPDIR/LICENSE $pn
		mkdir -p $pn/etc
		cp $rs $pn/etc
		mkdir -p $pn/$(dirname $lf)
		cp $TEMPDIR/$lf $pn/$lf
	done
	if [[ "$pn" == "loop-3.0" ]]
	then
		# generate LOOP docs
		mkdir -p $pn/doc/manual
		mkdir -p $pn/doc/release
		cd $TEMPDIR/doc
		lua "-epackage.path=[[../lua/?.lua;]]..package.path" build.lua sitemap.lua ../../$pn/doc
		cd ../..
		cp $TEMPDIR/doc/*.{css,gif} $pn/doc/
	elif [[ "$pn" == "looplib-2.0beta" ]]
	then
		# copy demos
		mkdir $pn/demo
		cp -R $TEMPDIR/demo/{debug,object} $pn/demo
	elif [[ "$pn" == "tuple-1.0beta" ]]
	then
		# copy demos
		mkdir $pn/demo
		cp $TEMPDIR/demo/tuples.lua $pn/demo
	elif [[ "$pn" == "cothread-0.1" ]]
	then
		# copy demos
		mkdir $pn/demo
		cp $TEMPDIR/demo/cothread/socket.lua $pn/demo
	fi
	tar -czvf $pn.tar.gz $pn/
	zip -r $pn.zip $pn/
	if [[ "$pn" != "loop-3.0" ]]
	then
		rm -fR $pn/
	fi
done

rm -fR $TEMPDIR/
