#!/bin/sh

SVNBASE=https://subversion.tecgraf.puc-rio.br/engsoftware/
VERSION=2.3
RELEASE=beta
PACKAGE=loop-$VERSION-$RELEASE

if [ ! -d $PACKAGE ]; then mkdir $PACKAGE; fi

svn export --force $SVNBASE/loop/trunk $PACKAGE

cd $PACKAGE
# build docs and remove unecessary files
cd doc; lua build.lua sitemap.lua .; cd ..
rm -f doc/docs_ClassTemplateDoc.html
rm -f doc/build.lua
rm -f doc/sitemap.lua
# remove this script
rm -fR etc
# remove test suite
rm -fR test
# remote LOOP classes that are still draft
rm -fR lua/loop/test
cd ..

tar -czvf $PACKAGE.tar.gz $PACKAGE/
zip -r $PACKAGE.zip $PACKAGE/
rm -fR $PACKAGE/
